# Generated by Django 5.2.7 on 2025-10-02 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО докладчика')),
                ('topic', models.CharField(max_length=300, verbose_name='Тема выступления')),
                ('duration', models.PositiveIntegerField(default=5, verbose_name='Длительность (мин)')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время старта')),
                ('is_running', models.BooleanField(default=False, verbose_name='Таймер запущен')),
                ('extra_time', models.IntegerField(default=0, verbose_name='Дополнительное время (сек)')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.speaker', verbose_name='Текущий докладчик')),
            ],
        ),
    ]
